INSERT INTO ROL (NOMBRE) VALUES ('MESERO');
INSERT INTO ROL (NOMBRE) VALUES ('COCINA');
INSERT INTO ROL (NOMBRE) VALUES ('CAJA');
INSERT INTO ROL (NOMBRE) VALUES ('ADMINISTRADOR');

INSERT INTO MESA (NUMERO_MESA, CAPACIDAD) VALUES (1, 4);
INSERT INTO MESA (NUMERO_MESA, CAPACIDAD) VALUES (2, 2);
INSERT INTO MESA (NUMERO_MESA, CAPACIDAD) VALUES (3, 6);
INSERT INTO MESA (NUMERO_MESA, CAPACIDAD) VALUES (4, 4);

INSERT INTO CATEGORIA_PRODUCTO (NOMBRE) VALUES ('ENTRADAS');
INSERT INTO CATEGORIA_PRODUCTO (NOMBRE) VALUES ('HAMBURGUESAS');
INSERT INTO CATEGORIA_PRODUCTO (NOMBRE) VALUES ('BEBIDAS');
INSERT INTO CATEGORIA_PRODUCTO (NOMBRE) VALUES ('ALTERNOS');

INSERT INTO USUARIO (ID_ROL, NOMBRE, APELLIDO, USERNAME, CORREO, CLAVE)
VALUES (1, 'Carlos', 'Mendez', 'mesero1', 'mesero1@lunaroja.com', 'password');


COMMIT;
